---
title: "Exploring Knitr"
author: "Robert Olendorf"
date: "February 26, 2016"
output: html_document
---

In order to look at more of document creation with Knitr we'll approach the document more like a research project. We'll keep using Markdown, but LaTeX wouldn't be much different from a Knitr standpoint. Create a new project called **_mtcars_**, go ahead an make it a Git repository as well. Then create a new Markdown document called **_mtcars_**, and delete everythign out except the YAML front matter. Edit that to yoru liking.

## Looking At The Data

We've already done this in the tour, but lets look at the data again.

```{r}
  head(mtcars)
  help(mtcars)
```

## Tables

Lets put some text in and display a table with the data. Add the following to your file.

```r
  The **_mtcars_** data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). A the first few rows are shown below.
  
  `` `` ``{r, mtcars-table}
    mtcars
  `` `` ``
```


The table could be much improved though. Knitr doesn't handle tables so we need a new package. We'll try the **Pander** package. This will require installing and requiring the **Pander** package, but we don't want to have to manually do it, so we'll add some code to check if it is installed. If **Pander** isn't installed it will be, then include the library into our environment. Put the following code near the top of your document, but below the front matter.

```
  `` ``` ``{r, echo=FALSE, results='hide', warning=FALSE, message=FALSE, error=TRUE}
  if(!require("pander"))
  {
    install.packages("pander", repos="http://cran.rstudio.com/", dependencies = TRUE)
  }
  
  library("pander", lib.loc="~/Library/R/3.2/library")
  
  `` `` ``

```

The code chunk options here tell Knitr not to show the code, results, warnings or any messages. This makes for a cleaner document. We are allowing errors to be shown, just in case.



